### PR TITLE
Minor Swift 2.3 correction

### PR DESCRIPTION
**Pull request by huguesbr**
Sorry I can't find a way to point to the `1.3.1` tag for my pull request. 
https://github.com/shaps80/InkKit/tree/1.3.1 is Swift 2.2
This PR update it to Swift 2.3

### CODE REVIEW

**Comment by huguesbr** [comment]
Check this compare for the right change: https://github.com/shaps80/InkKit/compare/1.3.1...huguesbr:swift-2.3

**Comment by huguesbr** [comment]
Happy Christmas 🎅 thanks

**Comment by shaps80** [comment]
No worries -- thanks for the contribution. Am updating the README now and then I'll update the Peek one too :)

**Comment by shaps80** [comment]
Oh and Merry Christmas to you too :)

**Pull request merged**
